# Generated by Django 5.1.2 on 2024-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cars', '0002_carmodel_remove_car_mark_alter_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='display_description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(
                choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('coupe', 'Coupe'),
                         ('convertible', 'Convertible'), ('crossover', 'Crossover')], default='sedan', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'),
                                            ('hybrid', 'Hybrid')], default='gasoline', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual',
                                   max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
