# Generated by Django 5.1.2 on 2024-11-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_body_type_remove_car_display_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
